import { DetalleVenta, Venta } from "@/shared/types/venta";
import {  DetalleVentaTabla, VentaDTO } from "../../types/sharedDTO.type";

export const mapVentaDTOToVenta = (venta: VentaDTO) : Venta => {
    return {
        codigo: venta.ve_codigo,
        cliente: venta.ve_cliente,
        operador: venta.ve_operador,
        deposito: venta.ve_deposito,
        moneda: venta.ve_moneda,
        fecha: new Date(venta.ve_fecha),
        factura: venta.ve_factura,
        credito: venta.ve_credito,
        saldo: venta.ve_saldo,
        total: venta.ve_total,
        vencimiento: new Date(venta.ve_vencimiento),
        estado: venta.ve_estado,
        devolucion: venta.ve_devolucion,
        procesado: venta.ve_procesado,
        descuento: venta.ve_descuento,
        cuotas: venta.ve_cuotas,
        cantCuotas: venta.ve_cantCuotas,
        obs: venta.ve_obs,
        vendedor: venta.ve_vendedor,
        sucursal: venta.ve_sucursal,
        metodo: venta.ve_metodo,
        aplicarA: venta.ve_aplicar_a,
        retencion: venta.ve_retencion,
        timbrado: venta.ve_timbrado,
        codeudor: venta.ve_codeudor,
        pedido: venta.ve_pedido,
        hora: venta.ve_hora,
        userPc: venta.ve_userpc,
        situacion: venta.ve_situacion,
        chofer: venta.ve_chofer,
        cdc: venta.ve_cdc,
        qr: venta.ve_qr,
        kmActual: venta.ve_km_actual,
        vehiculo: venta.ve_vehiculo,
        descTrabajo: venta.ve_desc_trabajo,
        kilometraje: venta.ve_kilometraje,
        servicio: venta.ve_servicio,
        siniestro: venta.ve_siniestro.toString(),
        mecanico: venta.ve_mecanico,
        cajaDefinicion: venta.ve_caja_definicion,
        confOperacion: venta.ve_conf_operacion,
    }
}


export const mapDetalleVentaDTOToDetalleVenta = (detalle: DetalleVentaTabla) : DetalleVenta => {
    return {
        deveVenta: detalle.deve_venta,
        deveArticulo: detalle.deve_articulo,
        deveCantidad: detalle.deve_cantidad,
        devePrecio: detalle.deve_precio,
        deveDescuento: detalle.deve_descuento,
        deveExentas: detalle.deve_exentas,
        deveCinco: detalle.deve_cinco,
        deveDiez: detalle.deve_diez,
        deveDevolucion: detalle.deve_devolucion,
        deveVendedor: detalle.deve_vendedor,
        deveColor: detalle.deve_color,
        deveBonificacion: detalle.deve_bonificacion,
        deveTalle: detalle.deve_talle,
        deveCodioot: detalle.deve_codioot,
        deveCosto: detalle.deve_costo,
        deveCostoArt: detalle.deve_costo_art,
        deveCincoX: detalle.deve_cinco_x,
        deveDiezX: detalle.deve_diez_x,
        editarNombre: detalle.deve_editar_nombre,
        lote: detalle.deve_lote,
        loteId: detalle.deve_lote_id,
        articuloEditado: detalle.deve_articulo_editado,
        deveDescripcionEditada: detalle.descripcion,
        codigoBarra: detalle.cod_barras,
        descripcion: detalle.descripcion,
        precioUnitario: detalle.precioUnitario,
        subtotal: detalle.subtotal,
    }
}

export const mapPuntoDeVentaToVenta = (venta: any) : Venta => {
    return  {
        codigo: venta.ventaId,
        cliente: venta.cliente,
        operador: venta.operador,
        deposito: venta.deposito,
        moneda: venta.moneda,
        fecha: new Date(venta.fecha),
        factura: venta.factura,
        credito: venta.credito,
        saldo: venta.saldo,
        total: venta.total,
        vencimiento: new Date(venta.vencimiento),
        estado: venta.estado,
        devolucion: venta.devolucion,
        procesado: venta.procesado,
        descuento: venta.descuento,
        cuotas: venta.cuotas,
        cantCuotas: venta.cantCuotas,
        obs: venta.obs,
        vendedor: venta.vendedor,
        sucursal: venta.sucursal,
        metodo: venta.metodo,
        aplicarA: venta.aplicarA,
        retencion: venta.retencion,
        timbrado: venta.timbrado,
        codeudor: venta.codeudor,
        pedido: venta.pedido,
        hora: venta.hora,
        userPc: venta.userpc,
        situacion: venta.situacion,
        chofer: venta.chofer,
        cdc: venta.ve_cdc,
        qr: venta.ve_qr,
        kmActual: venta.kmActual,
        vehiculo: venta.vehiculo,
        descTrabajo: venta.descTrabajo,
        kilometraje: venta.kilometraje,
        servicio: venta.servicio,
        siniestro: venta.siniestro,
        mecanico: venta.mecanico,
        cajaDefinicion: venta.cajaDefinicion,
        confOperacion: venta.confOperacion,
    }
}


export const mapDetalleVentaPuntoDeVentaToDetalleVenta = (ventaId: number, detalle: any) : DetalleVenta => {
    return {
        deveVenta: ventaId,
        deveArticulo: detalle.deve_articulo,
        deveCantidad: detalle.deve_cantidad,
        devePrecio: detalle.deve_precio,
        deveDescuento: detalle.deve_descuento,
        deveExentas: detalle.deve_exentas,
        deveCinco: detalle.deve_cinco,
        deveDiez: detalle.deve_diez,
        deveDevolucion: detalle.deve_devolucion,
        deveVendedor: detalle.deve_vendedor,
        deveColor: detalle.deve_color,
        deveBonificacion: detalle.deve_bonificacion,
        deveTalle: detalle.deve_talle,
        deveCodioot: detalle.deve_codioot,
        deveCosto: detalle.deve_costo,
        deveCostoArt: detalle.deve_costo_art,
        deveCincoX: detalle.deve_cinco_x,
        deveDiezX: detalle.deve_diez_x,
        editarNombre: detalle.deve_editar_nombre,
        lote: detalle.lote,
        loteId: detalle.deve_lote_id,
        articuloEditado: detalle.deve_articulo_editado,
        deveDescripcionEditada: detalle.descripcion,
        codigoBarra: detalle.cod_barras,
        descripcion: detalle.descripcion,
        precioUnitario: detalle.precioUnitario,
        subtotal: detalle.subtotal,
    }
}