import { ArticuloDTO } from "@/shared/types/articulos"
import { useState } from "react"

interface FormCrearArticuloProps {
    articuloAEditar?: ArticuloDTO;
}

export const FormCrearArticulo = ({articuloAEditar}: FormCrearArticuloProps) => {
    const [articuloDTO, setArticuloDTO] = useState<ArticuloDTO>({
        arCodigo: 0,
        arCodBarra: '',
        arUnidadMedida: 0,
        arDescripcion: '',
        arMarca: 0,
        arSubCategoria: 0,
        arUbicacion: 0,
        arMoneda: 0,
        arIva: 0,
        arPrecioCompraGuaranies: 0,
        arPrecioCompraDolar: 0,
        arPrecioCompraReal: 0,
        arPrecioCompraPeso: 0,
        arPrecioVentaGuaranies: 0,
        arPrecioVentaDolar: 0,
        arPrecioVentaReal: 0,
        arPrecioVentaPeso: 0,
        arStockMinimo: 0,
        arComision: 0,
        arGanancia: 0,
        arDescuentoMaximo: 0,
        arServicio: 0,
        arStockNegativo: 0,
        arMovPeso: 0,
        arObservaciones: '',
        arDisponible: 0,
        arEstado: 0,
        arRecargo: 0,
        arVencimiento: 0,
        arFechaVencimiento: '',
        arCbUnidad: 0,
        arKilos: 0,
        arFechaAlta: '',
        arUsuarioAlta: '',
        arLegal: 0,
        arNombreGenerico: '',
        arCodAcri: '',
        arFabricante: 0,
        arIndicacion: '',
        arTipoControl: 0,
        arPrecioVentaCredito: 0,
        arPrecioVentaMostrador: 0,
        arPais: 0,
        arVia: 0,
        arGananciaCredito: 0,
        arGananciaMostrador: 0,
        arLinea: 0,
        arFoto: '',
        arCantidadCaja: 0,
        arDocumento: '',
        arTransmision: 0,
        arEstadoVehiculo: 0,
        arCombustible: 0,
        arTraccion: 0,
        arChassi: '',
        arModelo: '',
        arChapa: '',
        arAnho: '',
        arKilometraje: 0,
        arColor: '',
        arCodInterno: '',
        arPrecioVentaDolarCredito: 0,
        arPrecioVentaDolarMostrador: 0,
        arGananciaDolarContado: 0,
        arGananciaDolarCredito: 0,
        arGananciaDolarMostrador: 0,
        arPrincipioActivo: '',
        arConcentracion: '',
        arKit: 0,
        arPrecioDescuentoDolar: 0,
        arCantidadDesde: 0,
        arPrecioDescuentoGuaranies: 0,
        arGananciaDescuento: 0,
        arMateriaPrima: 0,
        arMovBoutique: 0,
        arPromo: 0,
        arSeccion: 0,
        arIncluirInventario: 0,
        arReceptor: '',
        arDvl: 0,
        arDVentaL: 0,
        arSerie: '',
        arGarantia: 0,
        arLote: '',
        arSubUbicacion: 0,
        arEditarDesc: 0,
        arGranatura: 0,
        arMedida: 0,
        arCaracteristica: 0,
        arColores: 0,
        arAlicuotaIva: 0,
        arControlCodBarra: 0,
        arPrecio4: 0,
        arGanPrecio4: 0,
        arPrecioD4: 0,
        arGanPrecioD4: 0,
        arPvgxCaja: 0,
        arGangPvxCaja: 0,
        arControlRegistro: 0,
        arIgnorarMovCxc: 0,
        arActualizarPVenta: 0,
        arCostoMt2: 0,
        arBloque: 0,
        arPvgxCajaCred: 0,
        arPvgxCajaGCred: 0,
        arPvgxCajaMost: 0,
        arPvgxCajaGMost: 0,
        arPvgxCajaMost2: 0,
        arPvgxCajaGMost2: 0,
        arActCostoSubeProd: 0,
        arNoActCostoBajaProd: 0,
        arBloquear: 0,
        arFraccionamiento: 0,
        arCantFraccion: 0,
        arPrecioFraccion: 0,
        arComprimido: 0,
        arFormulaPintura: 0,
        arBasePintura: 0,
        arCodMarcasOrigen: '',
        arMsEnsamble: 0,
        arOpcionSet: 0,
        arOpcionSet10: 0,
        articuloLotes: [
            {
                alCodigo: 0,
                alArticulo: 0,
                articulo: 0,
                alDeposito: 0,
                alLote: '',
                alCantidad: 0,
                alVencimiento: '',
                alPreCompra: 0,
                alOrigen: 0,
                alSerie: '',
                alCodBarra: '',
                alNroTalle: '',
                alColor: 0,
                alTalle: 0,
                alRegistro: '',
            }
        ],
    })

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target;
        setArticuloDTO({ ...articuloDTO, [name]: value });
    }

    const handleCancelar = () => {
        setArticuloDTO({
            arCodigo: 0,
        arCodBarra: '',
        arUnidadMedida: 0,
        arDescripcion: '',
        arMarca: 0,
        arSubCategoria: 0,
        arUbicacion: 0,
        arMoneda: 0,
        arIva: 0,
        arPrecioCompraGuaranies: 0,
        arPrecioCompraDolar: 0,
        arPrecioCompraReal: 0,
        arPrecioCompraPeso: 0,
        arPrecioVentaGuaranies: 0,
        arPrecioVentaDolar: 0,
        arPrecioVentaReal: 0,
        arPrecioVentaPeso: 0,
        arStockMinimo: 0,
        arComision: 0,
        arGanancia: 0,
        arDescuentoMaximo: 0,
        arServicio: 0,
        arStockNegativo: 0,
        arMovPeso: 0,
        arObservaciones: '',
        arDisponible: 0,
        arEstado: 0,
        arRecargo: 0,
        arVencimiento: 0,
        arFechaVencimiento: '',
        arCbUnidad: 0,
        arKilos: 0,
        arFechaAlta: '',
        arUsuarioAlta: '',
        arLegal: 0,
        arNombreGenerico: '',
        arCodAcri: '',
        arFabricante: 0,
        arIndicacion: '',
        arTipoControl: 0,
        arPrecioVentaCredito: 0,
        arPrecioVentaMostrador: 0,
        arPais: 0,
        arVia: 0,
        arGananciaCredito: 0,
        arGananciaMostrador: 0,
        arLinea: 0,
        arFoto: '',
        arCantidadCaja: 0,
        arDocumento: '',
        arTransmision: 0,
        arEstadoVehiculo: 0,
        arCombustible: 0,
        arTraccion: 0,
        arChassi: '',
        arModelo: '',
        arChapa: '',
        arAnho: '',
        arKilometraje: 0,
        arColor: '',
        arCodInterno: '',
        arPrecioVentaDolarCredito: 0,
        arPrecioVentaDolarMostrador: 0,
        arGananciaDolarContado: 0,
        arGananciaDolarCredito: 0,
        arGananciaDolarMostrador: 0,
        arPrincipioActivo: '',
        arConcentracion: '',
        arKit: 0,
        arPrecioDescuentoDolar: 0,
        arCantidadDesde: 0,
        arPrecioDescuentoGuaranies: 0,
        arGananciaDescuento: 0,
        arMateriaPrima: 0,
        arMovBoutique: 0,
        arPromo: 0,
        arSeccion: 0,
        arIncluirInventario: 0,
        arReceptor: '',
        arDvl: 0,
        arDVentaL: 0,
        arSerie: '',
        arGarantia: 0,
        arLote: '',
        arSubUbicacion: 0,
        arEditarDesc: 0,
        arGranatura: 0,
        arMedida: 0,
        arCaracteristica: 0,
        arColores: 0,
        arAlicuotaIva: 0,
        arControlCodBarra: 0,
        arPrecio4: 0,
        arGanPrecio4: 0,
        arPrecioD4: 0,
        arGanPrecioD4: 0,
        arPvgxCaja: 0,
        arGangPvxCaja: 0,
        arControlRegistro: 0,
        arIgnorarMovCxc: 0,
        arActualizarPVenta: 0,
        arCostoMt2: 0,
        arBloque: 0,
        arPvgxCajaCred: 0,
        arPvgxCajaGCred: 0,
        arPvgxCajaMost: 0,
        arPvgxCajaGMost: 0,
        arPvgxCajaMost2: 0,
        arPvgxCajaGMost2: 0,
        arActCostoSubeProd: 0,
        arNoActCostoBajaProd: 0,
        arBloquear: 0,
        arFraccionamiento: 0,
        arCantFraccion: 0,
        arPrecioFraccion: 0,
        arComprimido: 0,
        arFormulaPintura: 0,
        arBasePintura: 0,
        arCodMarcasOrigen: '',
        arMsEnsamble: 0,
        arOpcionSet: 0,
        arOpcionSet10: 0,
        articuloLotes: [
            {
                alCodigo: 0,
                alArticulo: 0,
                articulo: 0,
                alDeposito: 0,
                alLote: '',
                alCantidad: 0,
                alVencimiento: '',
                alPreCompra: 0,
                alOrigen: 0,
                alSerie: '',
                alCodBarra: '',
                alNroTalle: '',
                alColor: 0,
                alTalle: 0,
                alRegistro: '',
            }
        ],
        })
    }
    
    return  (       
        <div>
            <button onClick={handleCancelar}>Cancelar</button>
            <input type="text" name="arDescripcion" value={articuloDTO.arDescripcion} onChange={handleChange}
            {
                ...articuloAEditar && (
                    <input type="text" name="arDescripcion" value={articuloDTO.arDescripcion} onChange={handleChange}
                    />
                )
            }
            />
        </div>
    )
}