export interface ArticuloBusqueda {
    idLote: number;
    lote: string;
    idArticulo: number;
    codigoBarra: string;
    descripcion: string;
  stockNegativo: number;
    precioCosto: number;
    precioVentaGuaranies: number;
    precioCredito: number;
    precioMostrador: number;
    precio4: number;
    precioCostoDolar: number;
    precioVentaDolar: number;
    precioCostoPesos: number;
    precioVentaPesos: number;
    precioCostoReal: number;
    precioVentaReal: number;
    vencimientoLote: string;
    cantidadLote: number;
    deposito: number;
    ubicacion: string;
    subUbicacion: string;
    marca: string;
    subcategoria: string;
    categoria: string;
    iva: number;
    vencimientoValidacion: number;
    ivaDescripcion: string;
    editarNombre: number;
    estadoVencimiento: string;
    proveedor: string;
    fechaUltimaVenta: string;
    fechaUltimaCompra: string;
    preCompra: number;
    principio_activo?: string;
    cantidad_caja?: number;
    precio_sugerido?: number;
    presentacion?: string;
    precompra?: number;
  }

  export interface ArticuloLote {
    id_articulo: number;
    codigo_interno: string;
  codigo_barra: string;
  codigo_barra_lote?: string;
  descripcion: string;
  stock: number;
  lotes: [
    {
      id: number;
      lote: string;
      cantidad: number;
      vencimiento: string;
    }
  ];
  depositos: [
    {
      codigo: number;
      descripcion: string;
      stock: number;
    }
  ];
  precio_costo: number;
  precio_venta: number;
  precio_credito: number;
  precio_mostrador: number;
  precio_4: number;
  ubicacion: string;
  sub_ubicacion: string;
  marca: string;
  categoria: string;
  subcategoria: string;
  proveedor_razon: string;
  fecha_ultima_compra: string;
  fecha_ultima_venta: string;
  talle: string;
  color: string;
}


export interface ArticuloDTO {
  arCodigo: number;
  arCodBarra?: string;
  arUnidadMedida: number;
  arDescripcion: string;
  arMarca: number;
  arSubCategoria: number;
  arUbicacion: number;
  arMoneda: number;
  arIva: number;
  arPrecioCompraGuaranies: number;
  arPrecioCompraDolar: number;
  arPrecioCompraReal: number;
  arPrecioCompraPeso: number;
  arPrecioVentaGuaranies: number;
  arPrecioVentaDolar: number;
  arPrecioVentaReal: number;
  arPrecioVentaPeso: number;
  arStockMinimo: number;
  arComision: number;
  arGanancia: number;
  arDescuentoMaximo: number;
  arServicio: number;
  arStockNegativo: number;
  arMovPeso: number;
  arObservaciones?: string;
  arDisponible: number;
  arEstado: number;
  arRecargo: number;
  arVencimiento: number;
  arFechaVencimiento: string;
  arCbUnidad: number;
  arKilos: number;
  arFechaAlta?: string;
  arUsuarioAlta?: string;
  arLegal: number;
  arNombreGenerico?: string;
  arCodAcri?: string;
  arFabricante: number;
  arIndicacion?: string;
  arTipoControl: number;
  arPrecioVentaCredito: number;
  arPrecioVentaMostrador: number;
  arPais: number;
  arVia: number;
  arGananciaCredito: number;
  arGananciaMostrador: number;
  arLinea: number;
  arFoto?: string;
  arCantidadCaja: number;
  arDocumento?: string;
  arTransmision: number;
  arEstadoVehiculo: number;
  arCombustible: number;
  arTraccion: number;
  arChassi?: string;
  arModelo?: string;
  arChapa?: string;
  arAnho?: string;
  arKilometraje: number;
  arColor?: string;
  arCodInterno?: string;
  arPrecioVentaDolarCredito: number;
  arPrecioVentaDolarMostrador: number;
  arGananciaDolarContado: number;
  arGananciaDolarCredito: number;
  arGananciaDolarMostrador: number;
  arPrincipioActivo?: string;
  arConcentracion?: string;
  arKit: number;
  arPrecioDescuentoDolar: number;
  arCantidadDesde: number;
  arPrecioDescuentoGuaranies: number;
  arGananciaDescuento: number;
  arMateriaPrima: number;
  arMovBoutique: number;
  arPromo: number;
  arSeccion: number;
  arIncluirInventario: number;
  arReceptor: string;
  arDvl: number;
  arDVentaL: number;
  arSerie: string;
  arGarantia: number;
  arLote?: string;
  arSubUbicacion: number;
  arEditarDesc: number;
  arGranatura: number;
  arMedida: number;
  arCaracteristica: number;
  arColores: number;
  arAlicuotaIva: number;
  arControlCodBarra: number;
  arOpcionSet: number;
  arOpcionSet10: number;
  arPrecio4: number;
  arGanPrecio4: number;
  arPrecioD4: number;
  arGanPrecioD4: number;
  arPvgxCaja: number;
  arGangPvxCaja: number;
  arControlRegistro: number;
  arIgnorarMovCxc: number;
  arActualizarPVenta: number;
  arCostoMt2: number;
  arBloque: number;
  arPvgxCajaCred: number;
  arPvgxCajaGCred: number;
  arPvgxCajaMost: number;
  arPvgxCajaGMost: number;
  arPvgxCajaMost2: number;
  arPvgxCajaGMost2: number;
  arActCostoSubeProd: number;
  arNoActCostoBajaProd: number;
  arBloquear: number;
  arFraccionamiento: number;
  arCantFraccion: number;
  arPrecioFraccion: number;
  arComprimido: number;
  arFormulaPintura: number;
  arBasePintura: number;
  arCodMarcasOrigen: string;
  arMsEnsamble: number;
  articuloLotes?: ArticuloLoteDTO[];
}

export interface ArticuloLoteDTO {
  alCodigo: number;
  alArticulo: number;
  articulo:number ;
  alDeposito: number;
  alLote: string;
  alCantidad: number;
  alVencimiento: string;
  alPreCompra: number;
  alOrigen: number;
  alSerie: string;
  alCodBarra: string;
  alNroTalle: string;
  alColor: number;
  alTalle: number;
  alRegistro: string;
}




