name: Deploy Frontend Clientes

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      cliente:
        description: 'Cliente específico a desplegar'
        required: true
        type: choice
        options:
          - gaesa
          - gaesademo
          - acricolor
          # - lobeck
          # - distriwembe
          # - concrecar
          # - bodega
          # - truckdiesel
          # - campomax
          # - lamberty
          # - rustimemo
          # - buda
          # - zimer
          # - mersan
          # - agrosertaneja
          # - caofa
          # - ferrehanh
jobs:
  deploy-single:
    if: github.event_name == 'workflow_dispatch'
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Update Configuration and Build
        run: |
          node scripts/updateConfig.js ${{ github.event.inputs.cliente }}
          npm run build

      - name: Deploy
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          CLIENTE: ${{ github.event.inputs.cliente }}
        run: |
          if [ "$CLIENTE" = "gaesa" ]; then
            TARGET_SERVER="192.168.102.6"
          elif [ "$CLIENTE" = "gaesademo" ]; then
            TARGET_SERVER="192.168.200.3"
          else
            TARGET_SERVER="192.168.200.3"
          fi
          
          sshpass -p "$SSH_PASSWORD" rsync -avz -e 'ssh -o StrictHostKeyChecking=no' --delete ./dist/ "$SSH_USER@$TARGET_SERVER:/var/www/$CLIENTE/dist/"

  deploy-all:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    strategy:
      matrix:
        cliente: [
          'gaesa',
          'gaesademo',
          'acricolor', 
          # 'lobeck', 
          # 'distriwembe', 
          # 'concrecar', 
          # 'bodega', 
          # 'truckdiesel', 
          # 'campomax', 
          # 'lamberty', 
          # 'rustimemo', 
          # 'buda', 
          # 'zimer', 
          # 'mersan', 
          # 'agrosertaneja', 
          # 'caofa', 
          # 'ferrehanh'
        ]
      # Permite que otros despliegues continúen si uno falla
      fail-fast: false
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Update Configuration and Build
        run: |
          node scripts/updateConfig.js ${{ matrix.cliente }}
          npm run build

      - name: Deploy
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          CLIENTE: ${{ matrix.cliente }}
        run: |
          if [ "$CLIENTE" = "gaesa" ]; then
            TARGET_SERVER="192.168.102.8"
          elif [ "$CLIENTE" = "gaesademo" ]; then
            TARGET_SERVER="192.168.200.3"
          else
            TARGET_SERVER="192.168.200.3"
          fi
          
          sshpass -p "$SSH_PASSWORD" rsync -avz -e 'ssh -o StrictHostKeyChecking=no' --delete ./dist/ "$SSH_USER@$TARGET_SERVER:/var/www/$CLIENTE/dist/"